--- #YAML:1.0
name: DBIx-MSAccess-Convert2Db
version: 1.05
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  Convert an MS Access database into a MySQL/Postgres/Other database
license: artistic
requires:
  Carp: 0
  DBI: 0
  DBIx::SQLEngine: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::MSAccess::Convert2Db:
    file: lib/DBIx/MSAccess/Convert2Db.pm
    version: 1.05
generated_by: Module::Build version 0.2611
